# Generated by Django 3.2.7 on 2021-09-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Python', '파이썬'), ('Web', '웹'), ('Django', '장고')], max_length=100),
        ),
    ]
